#!/usr/bin/env bash
# anvil-core -- the mod's own files, staged out of this checkout.
#
# THE RECIPE IS A LOOP OVER A DIRECTORY NOW, and that is the whole point of
# the layout. pkgs/anvil-core/payload/ is the $MODDIR overlay this package
# installs, laid out exactly as it lands: payload/etc/s6-rc/source/nginx
# becomes $MODDIR/etc/s6-rc/source/nginx and nothing here has to say so. A file
# added to that tree is shipped without an edit here.
#
# EVERY DIRECTORY HERE IS SHIPPED. There used to be a seed/ beside payload/
# holding anvil.conf.in, templated at build time and preserved across updates
# by installer/runFirmwareExe.sh -- user state that happened to ship with a
# default, and the one thing in this recipe an `apk upgrade` could not simply
# overwrite. anvil.conf is gone and so is the exception: what it configured is
# stated once each in the service that uses it, under payload/etc/s6-rc/source/,
# and ships as an ordinary package member like everything else.
#
# WHAT LIVES UNDER ANOTHER RECIPE, because ownership follows the component.
# This package used to hold all of it, for no better reason than being the
# first recipe written:
#
#   moonraker.conf, moonraker-custom.conf     pkgs/moonraker
#   ff-*.cfg, printer.base.cfg,               pkgs/klipper-config
#     chamber/<Machine>.cfg
#   klippy extras                             pkgs/klipper
#
# payload/prog/ holds the two files the printer reads from /usr/prog --
# firmwareExe and start.sh -- and this package owns the script that links them
# there: payload/bin/anvil-link-prog.sh. FlashForge's klipperDaemon is not
# among them and is left alone; that script says why.
#
# THE s6-rc SERVICE SOURCE IS HERE and is not compiled by this recipe.
# payload/etc/s6-rc/source/ is text, and payload/bin/anvil-s6-rc-compile.sh is
# what turns it into a database: the replica calls that script once the payload
# is assembled, and this package's postinst calls it again on a printer, so an
# `opkg upgrade` of these definitions changes what the next boot runs. The
# recipe itself compiles nothing, which is what keeps it buildable on a
# checkout that has never run a cross-compiler. Giving it
# PKG_BUILD_DEPENDS="s6-rc" would take that away.
set -euo pipefail
. ./bin/common.sh
. pkgs/lib.sh

pkg_begin anvil-core || exit 0
pkg_intree

# One entry per top-level name, rather than one cp of the whole tree, because
# pkg_stage takes a destination and `.` is not one -- and because the list it
# produces is exactly the list pkg_ship needs below.
_top=""
for _e in "$PKG_DIR"/payload/*; do
    [ -e "$_e" ] || continue
    _n=$(basename "$_e")
    pkg_stage "$_e" "$_n"
    _top="$_top $_n"
done
[ -n "$_top" ] || pkg_die "anvil-core: nothing under $PKG_DIR/payload"

# Executable bits, set here rather than inherited from the checkout, because
# a `run` that arrives without one is a service s6 can never start and reports
# only in its own log. cp -a preserved whatever git had; this makes it true
# regardless of what a contributor's umask did.
chmod +x "$PKG_WORK/stage$MODDIR/bin"/* "$PKG_WORK/stage$MODDIR/prog"/*
# The service definitions s6-supervise and the oneshot runner exec. `up` and
# `down` are execline command lines rather than files, so they are not here.
chmod +x "$PKG_WORK/stage$MODDIR"/etc/s6-rc/source/*/run 2>/dev/null || true

# THE FEED'S PUBLIC KEY, so a printer keeps trusting the feed after the .tgz
# that installed it is gone. The bootstrap copy comes off the USB stick
# (bin/build-payload.py), which is the only way the first install can verify
# anything -- this is the copy that survives it.
#
# Staged rather than committed: the key is generated by ./bin/apk-keygen.sh
# and its path lives in config.env, so the repository never holds either half.
# No key configured means an unsigned feed, which is a supported build.
# `etc` is already in $_top -- payload/etc/s6-rc puts it there -- so this
# stages into a tree pkg_ship already carries and must not be added again.
if [ -n "${APK_SIGN_KEY:-}" ] && [ -f "$APK_SIGN_KEY.pub" ]; then
    pkg_stage "$APK_SIGN_KEY.pub" "etc/apk/keys/anvil.pub"
    pkg_say "anvil-core: shipping the feed's public key"
fi

# WHERE TO FETCH FROM, beside the key that says whose packages to trust.
# apk reads <root>/etc/apk/repositories, so this one line is what makes
# `apk upgrade` on a printer mean the network rather than a USB stick.
#
# THE URL NAMES THE INDEX FILE, and that is the whole grammar: apk reads an
# entry ending .adb as a v3 index in place with the packages as its siblings,
# and anything else as a directory to look for <url>/<arch>/APKINDEX.tar.gz
# under. So this is the same shape the stick uses -- one feed layout, built
# once and exercised by every payload build.
#
# IT SHIPS BEFORE THE HOST EXISTS, deliberately. A printer cannot be told a
# URL by a feed it cannot reach, so the pointer has to travel in the .tgz that
# installs it; until the host answers, `apk upgrade` says the repository is
# unavailable and every other apk command is unaffected (`apk add ./file.apk`
# does not consult a repository at all).
#
# PKG_ARCH IS `all` AND THIS LINE NAMES AN ARCHITECTURE, which is not the
# contradiction it looks like: the string is a directory on a web server, not
# code, and $IPK_ARCH is the architecture of the feed this build produced.
mkdir -p "$PKG_WORK/gen"
cat > "$PKG_WORK/gen/repositories" <<EOF
# The Reforge package feed -- what \`apk update\` and \`apk upgrade\` read.
# Its packages are signed with the key in etc/apk/keys/. To stop this
# printer fetching updates, comment the line below out.
$FEED_URL/$IPK_ARCH/$PKG_INDEX_NAME
EOF
pkg_stage "$PKG_WORK/gen/repositories" "etc/apk/repositories"
pkg_say "anvil-core: feed is $FEED_URL/$IPK_ARCH/$PKG_INDEX_NAME"

# shellcheck disable=SC2086
pkg_ship $_top

# anvil-env.sh is SOURCED, not executed, and shipping it with an executable
# bit would invite somebody to run it. Checked because the chmod above is a
# glob and globs grow.
for _f in anvil-env.sh; do
    [ -x "$PKG_OUT/$_f" ] && pkg_die \
        "anvil-core: $_f is executable -- it is sourced, never run"
done

pkg_end
