#!/bin/sh
#
# Start klipepr 
#

PYTHON=/usr/prog/Python-3.8.2/bin/python3
KLIPPER=/usr/prog/klipper/klippy/klippy.py
#KLIPPER_CONF=/usr/prog/klipper/runConfig/printer.cfg
KLIPPER_CONF=/usr/data/config/printer.cfg
KLIPPER_LOG=/usr/data/logs/printer.log
PID_FILE=/run/klipper.pid
KLIPPER_UDS=/tmp/uds
KLIPPER_NICENESS=-20

start() {
    mkdir -p $(dirname $KLIPPER_LOG) # make sure the log directory exists
    start-stop-daemon -S -b -m -p $PID_FILE -N $KLIPPER_NICENESS --exec $PYTHON -- $KLIPPER $KLIPPER_CONF -l $KLIPPER_LOG -a $KLIPPER_UDS
}

stop() {
    start-stop-daemon -K -p $PID_FILE
}
restart() {
    stop
    sleep 2
    start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?
